### ISSUE TITLE
Can we get an arm template to create some the resources. It will reduce the steps to get this up and running drastically 

### ISSUE THREAD

**Issue by vikramhn** [Azure-Samples/azure-sql-db-session-recommender#8]
Can we get an arm template to create some the resources. It will reduce the steps to get this up and running drastically

**Comment by yorek** [comment]
Yep, work is going on to support AZD. Stay tuned :)

**Comment by yorek** [comment]
AZD-enabled deployment has been added. Enjoy! :)

**Comment by vikramhn** [comment]
Thank you
